'use strict'
const test=require('node:test'),assert=require('node:assert/strict'),express=require('express'),{randomUUID}=require('node:crypto'),{createRepairRouter}=require('./routes'),{createBridge}=require('../../subscription/bridge')
test('explicit chat preparation routes to the remote capability and retains one result link',async t=>{const {createDemoRouter}=require('../../routes/demoRouter'),http=require('node:http'),rows=[],id=randomUUID();let calls=0,modelCalls=0;const app=express();app.locals.conversationDemo=true;app.use(express.json());app.use(createDemoRouter({codeRepair:{start:async()=>{calls++;return {id,reused:calls>1}}},conversationStore:{appendTurn:row=>rows.push(row)},getAdapterFn:()=>{modelCalls++;throw Error('unexpected model')}}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)))
 const body={message:'香香，跟進最新診斷，準備受控修正。',conversationId:'repair-chat',workflowRequestId:randomUUID()};const post=b=>new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port:server.address().port,path:'/api/v1/demo/intake',method:'POST',headers:{host:'127.0.0.1:8090',origin:'http://127.0.0.1:8090','content-type':'application/json'}},res=>{let text='';res.on('data',c=>text+=c);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(text)}))});req.on('error',reject);req.end(JSON.stringify(b))})
 assert.equal((await post({...body,approved:true})).status,400);const r=await post(body);assert.equal(r.status,200);assert.equal(r.body.codeRepairRunId,id);assert.equal(r.body.servedBy,null);assert.match(r.body.reply,/等待你批准/);await post(body);assert.equal(rows.length,1);assert.equal(rows[0].codeRepairRunId,id);assert.equal(modelCalls,0)
 const router=require('../../capability/requestRouter').routeWorkRequest;for(const text of ['不要跟進最新診斷，準備受控修正','「跟進最新診斷，準備受控修正」','跟進最新診斷，準備受控修正並部署'])assert.equal(router(text),null)
})
test('repair routes accept only closed same-origin shapes and host runtime revision',async t=>{const calls=[],app=express();app.use(express.json());app.use(createRepairRouter({bootCommit:'b'.repeat(40),env:{READ_ACCESS:'on'},request:async b=>{calls.push(b);return {run:{id:'fixture'}}}}));const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(()=>new Promise(r=>server.close(r)));const base='http://127.0.0.1:'+server.address().port
 const headers={'content-type':'application/json','host':'127.0.0.1:8090','origin':'http://127.0.0.1:8090'},body={op:'prepare',diagnosisId:randomUUID(),requestId:randomUUID()}
 const send=(b,h=headers)=>new Promise((resolve,reject)=>{const req=require('node:http').request(base+'/api/v1/code-repair',{method:'POST',headers:h},res=>{res.resume();res.on('end',()=>resolve({status:res.statusCode}))});req.on('error',reject);req.end(JSON.stringify(b))})
 assert.equal((await send(body)).status,200);assert.equal(calls[0].bootCommit,'b'.repeat(40))
 for(const extra of [{bootCommit:'a'.repeat(40)},{path:'C:/secret'},{approved:true},{command:'node'}])assert.equal((await send({...body,...extra})).status,400)
 assert.equal((await send(body,{...headers,origin:'https://evil.example'})).status,403);assert.equal((await send({op:'apply',id:randomUUID()})).status,400);assert.equal(calls.length,1)
})
test('revoked live read flag prevents all bridge calls',async t=>{let calls=0;const app=express();app.use(createRepairRouter({bootCommit:'b'.repeat(40),env:{},request:()=>{calls++}}));const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(()=>new Promise(r=>server.close(r)));const response=await fetch('http://127.0.0.1:'+server.address().port+'/api/v1/code-repair');assert.equal(response.status,503);assert.equal(calls,0)})
test('bridge repair route requires internal bearer, rejects browser origins and path overrides',async t=>{let calls=0;const token='a'.repeat(64),server=createBridge({token,clientOptions:{},codeRepair:{isActive:()=>false,catalogue:()=>({workOrder:{}}),list:()=>[],get:()=>{calls++;return null}}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const base='http://127.0.0.1:'+server.address().port+'/code-repair',headers={'content-type':'application/json',authorization:'Bearer '+token};const send=(body,h=headers)=>fetch(base,{method:'POST',headers:h,body:JSON.stringify(body)})
 assert.equal((await send({op:'list'},{'content-type':'application/json'})).status,401);assert.equal((await send({op:'list'},{...headers,origin:'http://127.0.0.1:8090'})).status,401);assert.equal((await send({op:'get',id:randomUUID(),path:'C:/secret'})).status,400);assert.equal((await send({op:'get',id:randomUUID()})).status,200);assert.equal(calls,1)
})
