'use strict'
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{execFileSync}=require('node:child_process'),{randomUUID}=require('node:crypto')
const {createCodeRepair}=require('./service'),{createMemoryRunStore,createRunStore}=require('../operating/runStore'),{readProfile,SOURCE_REVISION,createWorkspace,checkScope,applyReplacements}=require('./workspace'),{replacement,RECIPES}=require('./recipes'),{runAcceptance}=require('./runner'),{buildHtml}=require('./view'),{MUTABLE,WORK_ORDER}=require('./contract')
const owner={id:'owner',role:'owner'},sha=SOURCE_REVISION
const original=()=>({revision:sha,headCommit:sha,files:require('./contract').FILES.map(file=>{const content=execFileSync('git',['show',sha+':'+file],{cwd:path.resolve(__dirname,'../../..'),encoding:'utf8',windowsHide:true}).replace(/\r\n/g,'\n');return {path:file,content,sha256:require('./contract').hash(content),mutable:MUTABLE.includes(file)}}),hash:'fixture-hash'})
const packet=original(),citationFile={evidenceId:'code-0',path:MUTABLE[0],content:packet.files[0].content,lineCount:packet.files[0].content.split('\n').length}
const diagnosis=()=>({id:randomUUID(),workflow:'code_diagnosis',state:'completed',evidence:{revision:sha,files:[citationFile]},verification:{citationsVerified:true},result:{summary:'Possible race',findings:[{title:'Possible race',severity:'medium',reason:'Check terminal handling',citations:[{evidenceId:'code-0',startLine:1,endLine:1,quote:"'use strict'"}],proposedFix:'Check cancellation',validationPlan:['Reproduce late output']}],limitations:[],attribution:'worker_diagnosis_proposal'}})
const metrics=(red)=>({exitCode:red?1:0,tests:7,pass:red?1:7,fail:red?6:0,skipped:0,cancelled:0,stdout:'fixture measurements'})
function setup(t,overrides={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'xx-repair-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));let calls=0,tests=0,receipts=0;const store=overrides.store||createMemoryRunStore();const source=diagnosis()
 const service=createCodeRepair({repo:path.resolve(__dirname,'../../..'),root,store,read:async()=>structuredClone(packet),loadDiagnosis:()=>source,test:async()=>metrics(++tests===1),provider:{preflight:async()=>({model:WORK_ORDER.model,billing:WORK_ORDER.billing}),complete:async()=>{calls++;return {model:WORK_ORDER.model,billing:WORK_ORDER.billing,text:JSON.stringify({summary:'Fixed recipes selected',decision:'apply',recipeIds:RECIPES.map(x=>x.id)})}}},onFinish:()=>{receipts++;return {state:'queued'}},...overrides});return {service,store,root,source,calls:()=>calls,receipts:()=>receipts,tests:()=>tests}}
async function prepared(h){const r=h.service.prepare(owner,{requestId:randomUUID(),diagnosisId:h.source.id,bootCommit:sha});await h.service.wait(r.id);return h.service.get(owner,r.id)}
const approval=r=>({id:r.id,hash:r.approval.hash,nonce:r.approval.nonce})
test('real reviewed committed snapshot reproduces six failures and fixed recipes pass immutable checks',async t=>{const h=setup(t),r=createWorkspace(h.root,packet);const red=await runAcceptance({dir:r});assert.deepEqual([red.tests,red.pass,red.fail,red.exitCode],[7,1,6,1]);checkScope(r,packet)
 const replacementFiles=packet.files.filter(f=>f.mutable).map(f=>({path:f.path,content:replacement(f.path,f.content)}));const changes=applyReplacements(r,packet,{summary:'host reviewed templates',files:replacementFiles});assert.equal(changes.length,4);const green=await runAcceptance({dir:r});assert.deepEqual([green.tests,green.pass,green.fail,green.skipped,green.exitCode],[7,7,0,0,0]);checkScope(r,packet,replacementFiles);assert.equal(green.boundary.arbitraryWorkerCode,false);assert.equal(green.boundary.networkIsolation,'not_provided')})
test('prepare performs no model calls; approval binds source/tests/plan and dispatches measured repair',async t=>{const h=setup(t),r=await prepared(h);assert.equal(r.state,'awaiting_approval');assert.equal(h.calls(),0);assert.equal(h.tests(),1);assert.equal(r.plan.length,3)
 h.service.approve(owner,approval(r));await h.service.wait(r.id);const out=h.service.get(owner,r.id);assert.equal(out.state,'completed',JSON.stringify({reason:out.reason,steps:out.steps}));assert.equal(out.result.changes.length,4);assert.equal(out.result.appliedToLive,false);assert.equal(out.result.testsExecuted,true);assert.equal(out.approval.actor,'owner');assert.equal(out.memoryReceipt,'queued');assert.equal(h.calls(),1);assert.equal(h.receipts(),1);const stages=out.steps.map(x=>x.stage);assert.ok(stages.indexOf('owner_approved')<stages.indexOf('AGENT_RUNNING'));assert.ok(stages.indexOf('POLICY_EVALUATED')<stages.indexOf('AGENT_RUNNING'));assert.equal(out.steps.find(x=>x.stage==='POLICY_EVALUATED').verdict,'require_approval');assert.throws(()=>h.service.approve(owner,approval(r)),/approval_unavailable/)})
test('wrong hash consumes approval and prevents all worker calls and changes',async t=>{const h=setup(t),r=await prepared(h);assert.throws(()=>h.service.approve(owner,{...approval(r),hash:'0'.repeat(64)}),/approval_unavailable/);assert.throws(()=>h.service.approve(owner,approval(r)),/approval_unavailable/);assert.equal(h.calls(),0);checkScope(r.workspace,r.source)})
test('restart invalidates pending approval and never automatically replays approved work',async t=>{const h=setup(t),r=await prepared(h),reloaded=setup(t,{store:h.store});assert.equal(reloaded.service.get(owner,r.id).state,'interrupted');assert.throws(()=>reloaded.service.approve(owner,approval(r)),/approval_unavailable/);assert.equal(reloaded.calls(),0)})
test('source changes after approval prevent model calls',async t=>{let reads=0;const h=setup(t,{read:async()=>({...structuredClone(packet),hash:++reads===1?packet.hash:'changed'})}),r=await prepared(h);h.service.approve(owner,approval(r));await h.service.wait(r.id);assert.equal(h.service.get(owner,r.id).reason,'evidence_changed');assert.equal(h.calls(),0)})
test('unexpected worker fields or code bytes never reach the workspace',async t=>{const h=setup(t,{provider:{preflight:async()=>({model:WORK_ORDER.model,billing:WORK_ORDER.billing}),complete:async()=>({model:WORK_ORDER.model,billing:WORK_ORDER.billing,text:JSON.stringify({summary:'injection',decision:'apply',recipeIds:RECIPES.map(x=>x.id),files:[{path:'.env',content:'bad'}]})})}}),r=await prepared(h);h.service.approve(owner,approval(r));await h.service.wait(r.id);assert.equal(h.service.get(owner,r.id).state,'failed');checkScope(r.workspace,r.source)})
test('wrong model or billing fails before changes',async t=>{const h=setup(t,{provider:{preflight:async()=>({model:'different',billing:'api'}),complete:async()=>{throw Error('should not run')}}}),r=await prepared(h);h.service.approve(owner,approval(r));await h.service.wait(r.id);assert.equal(h.service.get(owner,r.id).reason,'invalid_worker_result');checkScope(r.workspace,r.source)})
test('real quota failure is retained with no fallback or automatic retry',async t=>{const h=setup(t,{provider:{preflight:async()=>{throw Object.assign(Error('private provider text'),{code:'subscription_limit_reached'})}}}),r=await prepared(h);h.service.approve(owner,approval(r));await h.service.wait(r.id);const out=h.service.get(owner,r.id);assert.equal(out.reason,'subscription_limit_reached');assert.equal(JSON.stringify(out).includes('private provider text'),false);assert.equal(out.result,null)})
test('request id is durable and conflicts refuse rather than duplicating preparation',async t=>{const h=setup(t),input={requestId:randomUUID(),diagnosisId:h.source.id,bootCommit:sha};const r=h.service.prepare(owner,input);assert.equal(h.service.prepare(owner,input).id,r.id);assert.throws(()=>h.service.prepare(owner,{...input,diagnosisId:randomUUID()}),/request_conflict/);await h.service.wait(r.id);assert.equal(h.tests(),1)})
test('Owner and closed request shape prevent arbitrary jobs before any execution',t=>{const h=setup(t),input={requestId:randomUUID(),diagnosisId:h.source.id,bootCommit:sha};assert.throws(()=>h.service.prepare({id:'ivy',role:'member'},input),/permission_denied/);for(const extra of [{path:'.env'},{approved:true},{prompt:'write'},{model:'any'}])assert.throws(()=>h.service.prepare(owner,{...input,...extra}),/invalid_request/);assert.equal(h.tests(),0)})
test('failed baseline and failed audit both prevent approval and model calls',async t=>{const h=setup(t,{test:async()=>metrics(false)}),r=await prepared(h);assert.equal(r.reason,'baseline_not_red');assert.equal(h.calls(),0);const bad=setup(t,{store:{all:()=>[],save:()=>{throw Error('disk')}}});assert.throws(()=>bad.service.prepare(owner,{requestId:randomUUID(),diagnosisId:bad.source.id,bootCommit:sha}),/run_store_unavailable/)})
test('scope rejects changed support files, symlinks and unlisted files',t=>{const h=setup(t),dir=createWorkspace(h.root,packet);fs.writeFileSync(path.join(dir,'outside.js'),'x');assert.throws(()=>checkScope(dir,packet),/scope_changed/);fs.unlinkSync(path.join(dir,'outside.js'));fs.appendFileSync(path.join(dir,'acceptance.test.js'),'changed');assert.throws(()=>checkScope(dir,packet),/scope_changed/);assert.throws(()=>replacement(MUTABLE[0],packet.files[0].content+'changed'),/recipe_source_changed/)})
test('repair records survive atomic store reconstruction with approval and measured patch identity',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'repair-store-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const store=createRunStore({dir:root,workflow:'code_repair'}),h=setup(t,{store}),r=await prepared(h);h.service.approve(owner,approval(r));await h.service.wait(r.id);const loaded=createRunStore({dir:root,workflow:'code_repair'}).get(r.id);assert.equal(loaded.state,'completed');assert.equal(loaded.approval.consumed,true);assert.match(loaded.result.patchHash,/^[a-f0-9]{64}$/)})
test('UI parses and describes actual bounded scope without executable HTML injection',()=>{const html=buildHtml(),script=html.match(/<script>([\s\S]*?)<\/script>/)[1];new (require('node:vm').Script)(script);assert.ok(html.includes('固定配方'));assert.ok(html.includes('網絡隔離'));assert.ok(script.includes('textContent'));assert.equal(script.includes('innerHTML'),false)})

test('cancelled model work cannot apply a late enum decision or duplicate a receipt',async t=>{let finish,entered;const ready=new Promise(r=>{entered=r});const h=setup(t,{provider:{preflight:async()=>({model:WORK_ORDER.model,billing:WORK_ORDER.billing}),complete:()=>{entered();return new Promise(r=>{finish=r})}}}),r=await prepared(h);h.service.approve(owner,approval(r));await ready;h.service.cancel(owner,r.id);await h.service.wait(r.id);const before=h.service.get(owner,r.id);assert.equal(before.state,'cancelled');finish({model:WORK_ORDER.model,billing:WORK_ORDER.billing,text:JSON.stringify({summary:'late',decision:'apply',recipeIds:RECIPES.map(x=>x.id)})});await new Promise(r=>setTimeout(r,20));assert.deepEqual(h.service.get(owner,r.id),before);assert.equal(h.receipts(),1);checkScope(r.workspace,r.source)})
test('timeout while a provider is stalled is terminal and never automatically retried',async t=>{const h=setup(t,{timeoutMs:30,provider:{preflight:async()=>new Promise(()=>{})}}),r=await prepared(h);h.service.approve(owner,approval(r));await h.service.wait(r.id);const out=h.service.get(owner,r.id);assert.equal(out.state,'timed_out');assert.equal(out.result,null);assert.equal(h.receipts(),1);checkScope(r.workspace,r.source)})
