'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { spawnSync } = require('node:child_process')
const python = 'C:/Aroma/hindsight-runtime/Scripts/python.exe'
test('private recovery bundle restores receipt queue and coverage checkpoints, excludes credentials and detects damage', { skip: !fs.existsSync(python) }, t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'xx-recovery-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const program = `import sys,pathlib,json,hashlib\nsys.path.insert(0,sys.argv[1])\nfrom backupRecovery import stage_recovery, finish_recovery, verify_recovery, restore_files\nr=pathlib.Path(sys.argv[2]); data=r/'data'; data.mkdir()\nfor folder in ('memory-outbox','memory-capture','memory-consolidation','conversations','connections'):\n (data/folder).mkdir()\n(data/'memory-outbox'/'xx-a.json').write_text('{"id":"xx-a","text":"Pending receipt"}')\n(data/'memory-capture'/'settings.json').write_text('{"enabled":false}')\n(data/'conversations'/'c.json').write_text('{"messages":[{"content":"Historical chat"}]}')\n(data/'connections'/'oauth.json').write_text('{"refresh_token":"private-token"}')\n(data/'company-access.json').write_text('{"roles":["owner"]}')\nsnapshot=r/'snapshot.json'; content='{"format":1,"database":"xiangxiang_memory_core","tables":{"records":[{"body":{"source":{"kind":"admin_mail_history_import"},"details":{"state":{"processed":1234}}}}]}}'\npayload=json.loads(content); encode=lambda x:json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(',',':'))\nsnapshot.write_text(encode({'sha256':hashlib.sha256(encode(payload).encode()).hexdigest(),'snapshot':payload}))\nstaged=stage_recovery(r/'bundle',data)\nresult=finish_recovery(staged,snapshot)\nproof=verify_recovery(r/'bundle'); restored=restore_files(r/'bundle',r/'isolated')\nassert (r/'isolated'/'data'/'memory-outbox'/'xx-a.json').read_text().find('Pending receipt')>=0\nassert not (r/'isolated'/'data'/'connections').exists()\nassert 'private-token' not in (r/'bundle'/'manifest.json').read_text()\nassert proof['files']==4 and restored['files']==4\ntry:restore_files(r/'bundle',r/'isolated')\nexcept ValueError as e:assert str(e)=='destination_exists'\nelse:raise AssertionError('overwrote_restore')\nmanifest=json.loads((r/'bundle'/'manifest.json').read_text())['manifest']; object_file=r/'bundle'/'objects'/manifest['files'][0]['sha256']; object_file.write_bytes(b'corruption')\ntry:verify_recovery(r/'bundle')\nexcept ValueError as e:assert str(e)=='recovery_hash_mismatch'\nelse:raise AssertionError('damage_unseen')\nprint(json.dumps({'state':'verified','files':proof['files'],'retained':1234,'credentials':'excluded'}))`
  const run = spawnSync(python, ['-B', '-X', 'utf8', '-c', program, __dirname, root], { encoding: 'utf8', windowsHide: true })
  assert.equal(run.status, 0, run.stderr || run.stdout)
  assert.deepEqual(JSON.parse(run.stdout), { state: 'verified', files: 4, retained: 1234, credentials: 'excluded' })
})

test('canonical recovery validates 1,234 records, audit integrity and source checkpoint values before restore', { skip: !fs.existsSync(python) }, () => {
  const program = `import sys,json,hashlib\nsys.path.insert(0,sys.argv[1])\nfrom backupStructured import validate_snapshot\nfrom structured import encode\nrecords=[]; audit=[]\nfor i in range(1234):\n body={'id':'record-'+str(i),'version':1,'scope':'domain:email','source':{'kind':'admin_mail_message'},'details':{'mailbox':'adm@example.test'}}\n if i==1233:body['source']['kind']='admin_mail_history_import';body['details']['state']={'processed':1233,'state':'paused'}\n records.append({'sequence':i+1,'id':body['id'],'version':1,'body':encode(body)})\n event={'recordId':body['id'],'version':1,'snapshot':body}\n audit.append({'sequence':i+1,'record_id':body['id'],'body':encode(event),'previous_hash':None,'hash':hashlib.sha256(encode(event).encode()).hexdigest()})\nsnapshot={'format':1,'database':'xiangxiang_memory_core','tables':{'records':records,'audit':audit,'principals':[{'id':'ivy','body':encode({'scopes':['department:admin']})}],'access_audit':[{'sequence':1,'body':encode({'actor':'owner'})}]}}\nvalidate_snapshot(snapshot)\nassert json.loads(snapshot['tables']['records'][-1]['body'])['details']['state']['processed']==1233\nsnapshot['tables']['audit'][500]['body']=encode({'recordId':'record-500','version':1,'snapshot':{'altered':True}})\ntry:validate_snapshot(snapshot)\nexcept ValueError as e:assert str(e)=='backup_audit_invalid'\nelse:raise AssertionError('audit_damage_unseen')\nprint(json.dumps({'records':1234,'sourceCheckpoint':1233,'auditDamage':'rejected'}))`
  const run = spawnSync(python, ['-B', '-X', 'utf8', '-c', program, __dirname], { encoding: 'utf8', windowsHide: true })
  assert.equal(run.status, 0, run.stderr || run.stdout)
  assert.deepEqual(JSON.parse(run.stdout), { records: 1234, sourceCheckpoint: 1233, auditDamage: 'rejected' })
})

test('isolated file restore reports a write mismatch rather than claiming a verified recovery', { skip: !fs.existsSync(python) }, t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'xx-recovery-write-')); t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const program = `import sys,pathlib,json,hashlib\nsys.path.insert(0,sys.argv[1])\nimport backupRecovery as b\nr=pathlib.Path(sys.argv[2]); d=r/'data';(d/'memory-outbox').mkdir(parents=True);(d/'memory-outbox'/'xx-a.json').write_text('{"text":"receipt"}')\ns={'format':1,'database':'xiangxiang_memory_core','tables':{'records':[]}}\np=r/'snapshot.json';p.write_text(b.encode({'snapshot':s,'sha256':hashlib.sha256(b.encode(s).encode()).hexdigest()}))\nb.finish_recovery(b.stage_recovery(r/'bundle',d),p)\noriginal=b.write_new\ndef faulty(path,content):\n original(path,b'write-damaged' if 'isolated' in str(path) and path.name=='xx-a.json' else content)\nb.write_new=faulty\ntry:b.restore_files(r/'bundle',r/'isolated')\nexcept ValueError as e:assert str(e)=='recovery_restore_unconfirmed'\nelse:raise AssertionError('write_damage_unseen')\nprint('{"state":"write_damage_rejected"}')`
  const run = spawnSync(python, ['-B', '-X', 'utf8', '-c', program, __dirname, root], { encoding: 'utf8', windowsHide: true })
  assert.equal(run.status, 0, run.stderr || run.stdout)
  assert.equal(JSON.parse(run.stdout).state, 'write_damage_rejected')
})
