'use strict'
const test = require('node:test'), assert = require('node:assert/strict')
const { startupPlan, installScript } = require('./installAutostart.cjs')
const fs = require('node:fs'), os = require('node:os'), path = require('node:path'), { spawnSync } = require('node:child_process')
test('owner autostart targets node directly and repairs only the two fixed runtime shortcuts', () => {
  const plan = startupPlan({ repo: 'C:\\Aroma\\aroma-agent-backend', node: 'C:\\Program Files\\nodejs\\node.exe' })
  assert.equal(plan.length, 2)
  assert.deepEqual(plan.map(p => p.name), ['Xiangxiang Subscription Bridge.lnk', 'Xiangxiang Memory.lnk'])
  assert.equal(plan[0].target, 'C:\\Program Files\\nodejs\\node.exe')
  assert.equal(plan[0].arguments, '"C:\\Aroma\\aroma-agent-backend\\scripts\\memory\\serviceSupervisor.cjs" bridge')
  assert.equal(plan[1].arguments, '"C:\\Aroma\\aroma-agent-backend\\scripts\\memory\\serviceSupervisor.cjs" hindsight')
  const code = installScript(plan)
  assert.ok(code.includes('CreateShortcut'))
  assert.ok(code.includes('shortcut_identity_mismatch'))
  assert.ok(code.includes('Copy-Item -LiteralPath'))
  assert.ok(!code.includes('Set-ExecutionPolicy'))
  assert.ok(!code.includes('RunAs'))
  assert.ok(!code.includes('Register-ScheduledTask'))
  assert.ok(!code.includes('香香.lnk'))
})
test('startup plan rejects relative paths and shell-sensitive path values', () => {
  assert.throws(() => startupPlan({ repo: 'relative', node: 'node' }), /invalid_runtime_path/)
  assert.throws(() => startupPlan({ repo: 'C:\\Aroma\\bad"path', node: 'C:\\node.exe' }), /invalid_runtime_path/)
})
test('native Windows shortcut repair verifies legacy arguments and leaves foreign shortcuts untouched', { skip: process.platform !== 'win32' }, t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'memory-startup-test-'))
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
  const plan = startupPlan({ repo: 'C:\\Aroma\\aroma-agent-backend', node: process.execPath })
  const ps = path.join(process.env.SystemRoot, 'System32/WindowsPowerShell/v1.0/powershell.exe')
  const q = value => "'" + value.replace(/'/g, "''") + "'"
  const run = code => spawnSync(ps, ['-NoProfile', '-NonInteractive', '-Command', code], { windowsHide: true, encoding: 'utf8', timeout: 10000 })
  const setup = `$shell=New-Object -ComObject WScript.Shell; $s=$shell.CreateShortcut(${q(path.join(dir,plan[0].name))}); $s.TargetPath=${q(ps)}; $s.Arguments=${q('-NoProfile -ExecutionPolicy RemoteSigned -WindowStyle Hidden -File "' + plan[0].legacy + '"')}; $s.Save()`
  assert.equal(run(setup).status, 0)
  const code = installScript(plan).replace("$startup = [Environment]::GetFolderPath('Startup')", '$startup = ' + q(dir))
    .replace("$backup = Join-Path $env:LOCALAPPDATA ('AromaXiangXiang/startup-backups/' + [Guid]::NewGuid().ToString())", '$backup = ' + q(path.join(dir, 'backup')))
  const repaired = run(code)
  assert.equal(repaired.status, 0, repaired.stderr)
  const report = JSON.parse(repaired.stdout)
  assert.equal(report.length, 2); assert.ok(report.every(r => r.verified))
  assert.deepEqual(report.map(r => r.component), ['bridge', 'hindsight'])
  assert.ok(fs.existsSync(path.join(dir, 'backup', plan[0].name)))
  const foreign = `$shell=New-Object -ComObject WScript.Shell; $s=$shell.CreateShortcut(${q(path.join(dir,plan[1].name))}); $s.TargetPath='C:\\Windows\\notepad.exe'; $s.Arguments='foreign'; $s.Save()`
  assert.equal(run(foreign).status, 0)
  const before = fs.readFileSync(path.join(dir, plan[1].name))
  assert.notEqual(run(code).status, 0)
  assert.deepEqual(fs.readFileSync(path.join(dir, plan[1].name)), before)
})
