'use strict'
const { test } = require('node:test'), assert = require('node:assert/strict'), express = require('express')
const { createImageBodyParser } = require('./imageBodyParser')
test('only the image endpoint accepts a body above 50 KB and parse errors stay explicit without echoing input', async t => {
  const app = express(), ordinary = express.json({ limit: '50kb' }), images = createImageBodyParser()
  app.use((req, res, next) => (req.path === '/api/v1/demo/image-intake' ? images : ordinary)(req, res, next))
  app.post('*', (req, res) => res.json({ accepted: true }))
  app.use((error, req, res, next) => res.status(error.status || 500).json({ error: 'bounded' }))
  const server = app.listen(0, '127.0.0.1'); await new Promise(resolve => server.once('listening', resolve))
  t.after(() => new Promise(resolve => { server.closeAllConnections(); server.close(resolve) }))
  const send = (route, text) => fetch('http://127.0.0.1:' + server.address().port + route, { method: 'POST', headers: { 'content-type': 'application/json' }, body: text })
  const aboveOrdinary = JSON.stringify({ value: 'x'.repeat(60000) })
  assert.equal((await send('/api/v1/demo/image-intake', aboveOrdinary)).status, 200)
  assert.equal((await send('/api/v1/demo/intake', aboveOrdinary)).status, 413)
  const malformed = await send('/api/v1/demo/image-intake', '{private-content')
  assert.equal(malformed.status, 400); assert.equal((await malformed.text()).includes('private-content'), false)
  const oversized = await send('/api/v1/demo/image-intake', JSON.stringify({ value: 'x'.repeat(9 * 1024 * 1024) }))
  assert.equal(oversized.status, 413); const body = await oversized.json(); assert.ok(body.error.message); assert.equal(body.error.retryable, false)
})
