'use strict'
/**
 * leakSurface.helper.js — the part of a telemetry record a leak test is entitled to search.
 *
 * ══════════════════════════════════════════════════════════════════════════════
 * ⛔ WHY THIS EXISTS: A TIMESTAMP IS NOT A LEAK.
 *
 * A telemetry leak test asks 「did protected business content reach the log?」 and the obvious
 * way to ask it was `JSON.stringify(record).includes(value)`. It is wrong, because a serialized
 * record carries METADATA whose FORMAT nobody controls. Measured, with output preserved:
 *
 *     banned '69'   vs   "timestamp":"2026-08-23T01:23:16.692Z"    → .692 contains 69
 *     banned '8.72' vs   "timestamp":"...T20:15:18.723Z"           → 18.723 contains 8.72
 *
 * Nothing leaked. The tests failed anyway, at roughly one run in a thousand per timestamped
 * line — often enough to burn a release qualification and a forensic.
 *
 * ⛔ AND WHY THE FIRST FIX WAS REJECTED: SHAPE IS NOT METADATA.
 *
 * That version stripped ANY ISO-timestamp-shaped or UUID-shaped substring anywhere in the text,
 * and removed metadata key names at EVERY nesting level. Both are far too broad. A UUID is a
 * perfectly ordinary business value — an ingredient id in `sourceId`, a document id in `detail`
 * — and a nested key happening to be called `event` or `at` is not machine metadata. Under that
 * rule a real leak of an ingredient id would have been erased before the assertion ever saw it,
 * which is a worse defect than the one being fixed.
 *
 * ⛔ SO METADATA IS A STRUCTURAL FACT ABOUT AN EMITTER, NOT A SHAPE AND NOT A NAME.
 *
 * Exclusion is TOP-LEVEL ONLY, and only for keys proven metadata in the emitted schema:
 * `answerPlan.js:391` and `publicQueryEgressPlanner.js:282` both write
 * `timestamp: new Date().toISOString()` at the top level, beside a caller `requestId` and a
 * closed literal `event`. Nothing nested is exempt, and no value is judged by what it looks
 * like. `dropped[]`, `detail`, `query`, `sourceId`, `reason`, `outcome` — all still searched, in
 * full, whatever they happen to contain.
 * ══════════════════════════════════════════════════════════════════════════════
 */

/**
 * ⛔ TOP-LEVEL EMITTER METADATA — WHAT THE SCHEMAS ACTUALLY PROVE, NOT WHAT THEY MIGHT.
 *
 * Each entry is a key whose TOP-LEVEL value is generated by the emitter itself. Verified
 * against the two emitters these tests read:
 *
 *   answerPlan.js:391                event · timestamp · requestId
 *   publicQueryEgressPlanner.js:282  event · timestamp · requestId
 *
 * ⛔ correlationId IS NOT HERE, AND ITS ABSENCE IS THE POINT. An earlier version listed it
 * on the reasoning that a correlation id is obviously machine-generated. Neither emitter
 * emits one — it lives on OTHER emitters (intakeOutcomeLog, intakeDiagnostics) — so listing
 * it exempted a field these records can only carry as CONTENT. A speculative exemption is a
 * blind spot with a plausible excuse attached.
 *
 * ⛔ WHEN A FUTURE EMITTER GENUINELY ADDS ONE: do not widen this default. Pass that emitter
 * its own `metadataKeys` list, or extend this contract with the schema line that proves it
 * and a fixture that pins it. Every entry above can be pointed at a file and a line.
 *
 * ⛔ AND IT CONFERS NO AUTHORITY BELOW THE TOP LEVEL. `dropped[].event`, `detail.at` and
 * `payload.requestId` are content and stay searchable.
 */
const METADATA_KEYS = Object.freeze(['timestamp', 'requestId', 'event'])

/**
 * The content surface of a structured record: the same object minus top-level metadata keys.
 *
 * ⛔ SHALLOW ON PURPOSE. The previous version recursed, which made every nested `event` and `at`
 * invisible to the leak search. Nested structures are returned untouched, by reference-free
 * clone, so a leak anywhere inside them still trips the assertion.
 */
function contentSurfaceOf (record, metadataKeys = METADATA_KEYS) {
  if (!record || typeof record !== 'object' || Array.isArray(record)) return record
  const out = {}
  for (const [k, v] of Object.entries(record)) {
    if (metadataKeys.includes(k)) continue
    out[k] = v
  }
  return JSON.parse(JSON.stringify(out))
}

/** The searchable text of a structured record — top-level metadata removed, all else intact. */
const contentTextOf = (record, metadataKeys) => JSON.stringify(contentSurfaceOf(record, metadataKeys))

/**
 * ⛔ FOR A RAW LOG LINE, THE PAYLOAD IS PARSED — NEVER PATTERN-SCRUBBED.
 *
 * `a4EgressProvenance` captures whole console lines of the form `[AROMA-EGRESS-PLAN] {json}`.
 * The honest projection is to find the JSON, parse it, apply the same top-level structural rule
 * and re-serialize. The emitter prefix is kept.
 *
 * ⛔ AND IT FAILS SAFE. A line with no parseable JSON payload is returned COMPLETELY UNCHANGED,
 * so an unrecognised shape is searched in full rather than silently trimmed. The dangerous
 * direction here is removing too much, so anything not understood is left alone.
 */
function contentTextOfLogLine (line, metadataKeys = METADATA_KEYS) {
  const s = String(line == null ? '' : line)
  const i = s.indexOf('{')
  if (i < 0) return s
  const head = s.slice(0, i)
  let parsed
  try { parsed = JSON.parse(s.slice(i)) } catch (_) { return s } // not JSON → search everything
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) return s
  return head + contentTextOf(parsed, metadataKeys)
}

/** Every captured line, each projected independently. Non-JSON lines pass through untouched. */
const contentTextOfLogLines = (lines, metadataKeys) =>
  (Array.isArray(lines) ? lines : []).map((l) => contentTextOfLogLine(l, metadataKeys)).join('\n')

module.exports = {
  METADATA_KEYS,
  contentSurfaceOf,
  contentTextOf,
  contentTextOfLogLine,
  contentTextOfLogLines
}
