'use strict'
const test = require('node:test'), assert = require('node:assert/strict'), { randomUUID } = require('node:crypto')
const { createPlanner } = require('./service'), { PROFILES, hash } = require('./contract'), { createTasks } = require('../projectTasks/service'), { createRegistry, FILES } = require('../projectTasks/contract'), { createMemoryRunStore } = require('../operating/runStore')
const OWNER = { id: 'owner', role: 'owner' }, HEAD = 'a'.repeat(40)
test('actual planner and task services bind edited criteria, protected tests and distinct approval stages without automatic coding', async () => {
  const plans = createMemoryRunStore(), records = createMemoryRunStore(), registry = createRegistry(records), calls = []
  const files = Object.fromEntries(FILES.map(file => [file, "'use strict'\n"]))
  const evidence = { project: 'aroma-agent-backend', profile: 'context', revision: HEAD, bootCommit: HEAD, committedOnly: true, files: PROFILES.context.map((path, i) => ({ path, evidenceId: 'plan-' + i, content: files[path], lineCount: 2, sha256: hash(files[path]) })) }
  const generated = { testCode: "const test=require('node:test'),assert=require('node:assert/strict');test('first',()=>assert.equal(1,1));test('second',()=>assert.equal(2,2));test('third',()=>assert.equal(3,3));", expectedTests: 3 }
  const tasks = createTasks({ store: records, enabled: () => true, sourceFor: d => ({ read: async () => ({ evidence: { bootCommit: HEAD, recipe: d.workOrder.recipe }, hash: 'b'.repeat(64), order: { files: { ...files, ...d.tests } } }), verify: async () => {} }), provider: { preflight: async () => ({ model: 'gpt-6.1-sol', billing: 'chatgpt-subscription' }), complete: async () => { calls.push('draft'); return { model: 'gpt-6.1-sol', billing: 'chatgpt-subscription', text: JSON.stringify(generated) } } }, review: async () => { calls.push('review'); return { verdict: 'pass', billing: 'claude-subscription' } }, prepareWork: async b => { calls.push('work-preparation'); return { run: { id: randomUUID(), workOrder: registry.resolve(b.recipe).workOrder }, approval: { nonce: 'separate-coding-ticket' } } } })
  const planner = createPlanner({ bootCommit: HEAD, store: plans, source: { verify: () => {}, read: async () => ({ state: 'ok', retrievedAt: new Date().toISOString(), evidence, hash: hash(JSON.stringify(evidence)) }) }, provider: { preflight: async () => ({ model: 'gpt-6.1-sol', billing: 'chatgpt-subscription' }), complete: async () => ({ model: 'gpt-6.1-sol', billing: 'chatgpt-subscription', text: JSON.stringify({ goal: 'Snapshot changes', steps: ['inspect'], acceptanceChecks: ['independent'], questions: [], risks: [], capability: { status: 'supported', explanation: 'Fits the registered files', missingCapabilities: [] }, citations: [{ evidenceId: 'plan-0', startLine: 1, endLine: 1, quote: "'use strict'" }] }) }) }, registerTask: b => { const { op, ...input } = b; assert.equal(op, 'start'); return tasks.start(OWNER, input) }, findTask: requestId => tasks.find(OWNER, { requestId }) })
  const plan = planner.start(OWNER, { message: '香香，幫我改善即時資料快照', requestId: randomUUID(), conversationId: 'chat-' + randomUUID() }); await planner.wait(plan.id); assert.deepEqual(calls, [])
  const input = { id: plan.id, requestId: randomUUID(), goal: 'Owner edited goal', criteria: ['Owner edited criterion'], editable: [FILES[1]] }, linked = await planner.registerTask(OWNER, input); await tasks.settled()
  const task = tasks.get(OWNER, linked.run.taskRunId); assert.equal(task.run.state, 'awaiting_approval'); assert.deepEqual(task.run.input.criteria, input.criteria); assert.deepEqual(task.run.registration.workOrder.allowedFiles, [FILES[1]]); assert.deepEqual(task.run.registration.workOrder.readonlyFiles, [FILES[0]]); assert.deepEqual(calls, ['draft', 'review']); assert.throws(() => registry.resolve(task.run.registration.workOrder.recipe))
  await tasks.approve(OWNER, { id: task.run.id, hash: task.approval.hash, nonce: task.approval.nonce }); assert.equal(tasks.get(OWNER, task.run.id).run.workRunId, null)
  const work = await tasks.prepare(OWNER, { id: task.run.id, requestId: randomUUID() }); assert.equal(work.work.approval.nonce, 'separate-coding-ticket'); assert.deepEqual(calls, ['draft', 'review', 'work-preparation']); assert.equal(JSON.stringify(plans.all()).includes(task.approval.nonce), false)
  assert.equal(tasks.find(OWNER, { requestId: input.requestId }).run.workRunId, work.work.run.id); assert.equal(tasks.find(OWNER, { requestId: randomUUID() }).run, null); assert.throws(() => tasks.find({ id: 'ivy', role: 'member' }, { requestId: input.requestId }), /permission_denied/)
  assert.equal(planner.get(OWNER, plan.id).taskRunId, task.run.id); await assert.rejects(planner.prepare(OWNER, { id: plan.id, requestId: randomUUID() }))
})
